# Generated by Django 3.1.7 on 2024-07-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_store2', '0003_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_code',
            field=models.IntegerField(verbose_name=range(999, 9999)),
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
