# Generated by Django 4.2.14 on 2024-07-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_store2', '0004_auto_20240718_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_code',
        ),
    ]
