# Generated by Django 4.2.14 on 2024-07-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_store2', '0005_remove_users_user_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
