# Generated by Django 4.2.14 on 2024-07-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_store2', '0007_alter_customer_table_alter_orders_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
