# Generated by Django 4.0.5 on 2024-07-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_store2', '0009_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_email',
            field=models.CharField(default='example@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_phone',
            field=models.IntegerField(default=0),
        ),
    ]
