# Generated by Django 4.0.5 on 2024-07-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_store2', '0011_alter_customer_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
