# Generated by Django 4.0.5 on 2024-07-23 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_store2', '0013_alter_customer_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_customer',
            field=models.ForeignKey(db_column='order_customer_phone', default=705951417, on_delete=django.db.models.deletion.CASCADE, to='super_store2.customer', to_field='customer_phone'),
        ),
    ]
