# Generated by Django 4.0.5 on 2024-07-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_store2', '0014_orders_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_customer',
            field=models.ForeignKey(db_column='order_customer_phone', on_delete=django.db.models.deletion.CASCADE, to='super_store2.customer', to_field='customer_phone'),
        ),
    ]
