name: Django CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
        mysql-version: [8.0, 5.7]

    services:
      mysql:
        image: mysql:${{ matrix.mysql-version }}
        env:
          DB_DATABASE: super_store
          DB_USER: root
          DB_PASSWORD: root
        ports:
          - 13306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        env:
          AFRICASTALKING_USERNAME: ${{ secrets.AFRICASTALKING_USERNAME }}
          AFRICASTALKING_API_KEY: ${{ secrets.AFRICASTALKING_API_KEY }}
        run: |
          python manage.py test

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start

      - name: Run migrations
        env:
          DATABASE_URL: mysql://user:password@<container_ip_or_hostname>:3306/super_store
        run: |
          python manage.py migrate
      - name: Run tests
        env:
          DATABASE_URL: mysql://user:password@<container_ip_or_hostname>:3306/super_store
        run: |
          python manage.py test
