name: Django CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
        mysql-version: [8.0, 5.7]

    services:
      mysql:
        image: mysql:${{ matrix.mysql-version }}
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: super_store
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 13306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        env:
          AFRICASTALKING_USERNAME: ${{ secrets.AFRICASTALKING_USERNAME }}
          AFRICASTALKING_API_KEY: ${{ secrets.AFRICASTALKING_API_KEY }}
        run: |
          python manage.py test
      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for database connection..."
            sleep 5
          done
      - name: Run migrations
        env:
          DATABASE_URL: mysql://user:password@127.0.0.1:3306/super_store
        run: |
          python manage.py migrate
      - name: Run tests
        env:
          DATABASE_URL: mysql://user:password@127.0.0.1:3306/super_store
        run: |
          python manage.py test
